class WilayahData {
  static const List<Map<String, String>> data = [
    {
      'kode_wilayah': '3303010001',
      'nama_desa': 'Kedungbenda',
      'kode_kel': '001',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010002',
      'nama_desa': 'Bokol',
      'kode_kel': '002',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010003',
      'nama_desa': 'Pelumutan',
      'kode_kel': '003',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010004',
      'nama_desa': 'Majatengah',
      'kode_kel': '004',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010005',
      'nama_desa': 'Kedunglegok',
      'kode_kel': '005',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010006',
      'nama_desa': 'Kemangkon',
      'kode_kel': '006',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010007',
      'nama_desa': 'Panican',
      'kode_kel': '007',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010008',
      'nama_desa': 'Bakulan',
      'kode_kel': '008',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010009',
      'nama_desa': 'Karangkemiri',
      'kode_kel': '009',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010010',
      'nama_desa': 'Pegandekan',
      'kode_kel': '010',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010011',
      'nama_desa': 'Senon',
      'kode_kel': '011',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010012',
      'nama_desa': 'Sumilir',
      'kode_kel': '012',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010013',
      'nama_desa': 'Kalialang',
      'kode_kel': '013',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010014',
      'nama_desa': 'Karangtengah',
      'kode_kel': '014',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010015',
      'nama_desa': 'Muntang',
      'kode_kel': '015',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010016',
      'nama_desa': 'Gambarsari',
      'kode_kel': '016',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010017',
      'nama_desa': 'Toyareka',
      'kode_kel': '017',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010018',
      'nama_desa': 'Jetis',
      'kode_kel': '018',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303010019',
      'nama_desa': 'Majasem',
      'kode_kel': '019',
      'kode_kec': '010',
      'kecamatan': 'Kemangkon',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020001',
      'nama_desa': 'Tidu',
      'kode_kel': '001',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020002',
      'nama_desa': 'Wirasaba',
      'kode_kel': '002',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020003',
      'nama_desa': 'Kembangan',
      'kode_kel': '003',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020004',
      'nama_desa': 'Cipawon',
      'kode_kel': '004',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020005',
      'nama_desa': 'Karangcengis',
      'kode_kel': '005',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020006',
      'nama_desa': 'Karanggedang',
      'kode_kel': '006',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020007',
      'nama_desa': 'Karangnangka',
      'kode_kel': '007',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020008',
      'nama_desa': 'Kutawis',
      'kode_kel': '008',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020009',
      'nama_desa': 'Kebutuh',
      'kode_kel': '009',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020010',
      'nama_desa': 'Penaruban',
      'kode_kel': '010',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020011',
      'nama_desa': 'Kedungjati',
      'kode_kel': '011',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020012',
      'nama_desa': 'Bukateja',
      'kode_kel': '012',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020013',
      'nama_desa': 'Majasari',
      'kode_kel': '013',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303020014',
      'nama_desa': 'Bajong',
      'kode_kel': '014',
      'kode_kec': '020',
      'kecamatan': 'Bukateja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030001',
      'nama_desa': 'Bandingan',
      'kode_kel': '001',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030002',
      'nama_desa': 'Lamuk',
      'kode_kel': '002',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030003',
      'nama_desa': 'Sokanegara',
      'kode_kel': '003',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030004',
      'nama_desa': 'Gumiwang',
      'kode_kel': '004',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030005',
      'nama_desa': 'Krenceng',
      'kode_kel': '005',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030006',
      'nama_desa': 'Nangkasawit',
      'kode_kel': '006',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030007',
      'nama_desa': 'Pandansari',
      'kode_kel': '007',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030008',
      'nama_desa': 'Kejobong',
      'kode_kel': '008',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030009',
      'nama_desa': 'Langgar',
      'kode_kel': '009',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030010',
      'nama_desa': 'Timbang',
      'kode_kel': '010',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030011',
      'nama_desa': 'Nangkod',
      'kode_kel': '011',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030012',
      'nama_desa': 'Kedarpan',
      'kode_kel': '012',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303030013',
      'nama_desa': 'Pangempon',
      'kode_kel': '013',
      'kode_kec': '030',
      'kecamatan': 'Kejobong',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040001',
      'nama_desa': 'Lamongan',
      'kode_kel': '001',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040002',
      'nama_desa': 'Tejasari',
      'kode_kel': '002',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040003',
      'nama_desa': 'Cilapar',
      'kode_kel': '003',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040004',
      'nama_desa': 'Penolih',
      'kode_kel': '004',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040005',
      'nama_desa': 'Sinduraja',
      'kode_kel': '005',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040006',
      'nama_desa': 'Selakambang',
      'kode_kel': '006',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040007',
      'nama_desa': 'Selanegara',
      'kode_kel': '007',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040008',
      'nama_desa': 'Kaligondang',
      'kode_kel': '008',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040009',
      'nama_desa': 'Brecek',
      'kode_kel': '009',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040010',
      'nama_desa': 'Sempor Lor',
      'kode_kel': '010',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040011',
      'nama_desa': 'Penaruban',
      'kode_kel': '011',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040012',
      'nama_desa': 'Kalikajar',
      'kode_kel': '012',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040013',
      'nama_desa': 'Kembaran Wetan',
      'kode_kel': '013',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040014',
      'nama_desa': 'Slinga',
      'kode_kel': '014',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040015',
      'nama_desa': 'Arenan',
      'kode_kel': '015',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040016',
      'nama_desa': 'Sidanegara',
      'kode_kel': '016',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040017',
      'nama_desa': 'Pagerandong',
      'kode_kel': '017',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303040018',
      'nama_desa': 'Sidareja',
      'kode_kel': '018',
      'kode_kec': '040',
      'kecamatan': 'Kaligondang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050001',
      'nama_desa': 'Bojong',
      'kode_kel': '001',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050003',
      'nama_desa': 'Kedungmenjangan',
      'kode_kel': '003',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050005',
      'nama_desa': 'Bancar',
      'kode_kel': '005',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050006',
      'nama_desa': 'Purbalingga Wetan',
      'kode_kel': '006',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050007',
      'nama_desa': 'Penambongan',
      'kode_kel': '007',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050008',
      'nama_desa': 'Purbalingga Kidul',
      'kode_kel': '008',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050009',
      'nama_desa': 'Kandanggampang',
      'kode_kel': '009',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050010',
      'nama_desa': 'Purbalingga Kulon',
      'kode_kel': '010',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050011',
      'nama_desa': 'Purbalingga Lor',
      'kode_kel': '011',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050012',
      'nama_desa': 'Kembaran Kulon',
      'kode_kel': '012',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050013',
      'nama_desa': 'Wirasana',
      'kode_kel': '013',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050002',
      'nama_desa': 'Toyareja',
      'kode_kel': '002',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303050004',
      'nama_desa': 'Jatisaba',
      'kode_kel': '004',
      'kode_kec': '050',
      'kecamatan': 'Purbalingga',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060011',
      'nama_desa': 'Mewek',
      'kode_kel': '011',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060012',
      'nama_desa': 'Karangmanyar',
      'kode_kel': '012',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060013',
      'nama_desa': 'Kalikabong',
      'kode_kel': '013',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060001',
      'nama_desa': 'Jompo',
      'kode_kel': '001',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060002',
      'nama_desa': 'Rabak',
      'kode_kel': '002',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060003',
      'nama_desa': 'Blater',
      'kode_kel': '003',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060004',
      'nama_desa': 'Manduraga',
      'kode_kel': '004',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060005',
      'nama_desa': 'Karangsari',
      'kode_kel': '005',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060006',
      'nama_desa': 'Kalimanah Kulon',
      'kode_kel': '006',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060007',
      'nama_desa': 'Sidakangen',
      'kode_kel': '007',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060008',
      'nama_desa': 'Karangpetir',
      'kode_kel': '008',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060009',
      'nama_desa': 'Kalimanah Wetan',
      'kode_kel': '009',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060010',
      'nama_desa': 'Grecol',
      'kode_kel': '010',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060014',
      'nama_desa': 'Selabaya',
      'kode_kel': '014',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060015',
      'nama_desa': 'Klapasawit',
      'kode_kel': '015',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060016',
      'nama_desa': 'Kedungwuluh',
      'kode_kel': '016',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303060017',
      'nama_desa': 'Babakan',
      'kode_kel': '017',
      'kode_kec': '060',
      'kecamatan': 'Kalimanah',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070001',
      'nama_desa': 'Karanglewas',
      'kode_kel': '001',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070002',
      'nama_desa': 'Munjul',
      'kode_kel': '002',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070003',
      'nama_desa': 'Sumingkir',
      'kode_kel': '003',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070004',
      'nama_desa': 'Meri',
      'kode_kel': '004',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070005',
      'nama_desa': 'Kutasari',
      'kode_kel': '005',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070006',
      'nama_desa': 'Karangklesem',
      'kode_kel': '006',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070007',
      'nama_desa': 'Karangreja',
      'kode_kel': '007',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070008',
      'nama_desa': 'Karangaren',
      'kode_kel': '008',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070009',
      'nama_desa': 'Limbangan',
      'kode_kel': '009',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070010',
      'nama_desa': 'Cendana',
      'kode_kel': '010',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070011',
      'nama_desa': 'Candiwulan',
      'kode_kel': '011',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070012',
      'nama_desa': 'Karangcegak',
      'kode_kel': '012',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070013',
      'nama_desa': 'Candinata',
      'kode_kel': '013',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303070014',
      'nama_desa': 'Karangjengkol',
      'kode_kel': '014',
      'kode_kec': '070',
      'kecamatan': 'Kutasari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080001',
      'nama_desa': 'Karangturi',
      'kode_kel': '001',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080002',
      'nama_desa': 'Onje',
      'kode_kel': '002',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080003',
      'nama_desa': 'Sindang',
      'kode_kel': '003',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080004',
      'nama_desa': 'Tangkisan',
      'kode_kel': '004',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080005',
      'nama_desa': 'Kradenan',
      'kode_kel': '005',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080006',
      'nama_desa': 'Lambur',
      'kode_kel': '006',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080007',
      'nama_desa': 'Selaganggeng',
      'kode_kel': '007',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080008',
      'nama_desa': 'Mangunegara',
      'kode_kel': '008',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080009',
      'nama_desa': 'Karangnangka',
      'kode_kel': '009',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080010',
      'nama_desa': 'Mrebet',
      'kode_kel': '010',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080011',
      'nama_desa': 'Bojong',
      'kode_kel': '011',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080012',
      'nama_desa': 'Serayu Karanganyar',
      'kode_kel': '012',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080013',
      'nama_desa': 'Serayu Larangan',
      'kode_kel': '013',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080014',
      'nama_desa': 'Campakoah',
      'kode_kel': '014',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080015',
      'nama_desa': 'Pagerandong',
      'kode_kel': '015',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080016',
      'nama_desa': 'Cipaku',
      'kode_kel': '016',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080017',
      'nama_desa': 'Binangun',
      'kode_kel': '017',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080018',
      'nama_desa': 'Pengalusan',
      'kode_kel': '018',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303080019',
      'nama_desa': 'Sangkanayu',
      'kode_kel': '019',
      'kode_kec': '080',
      'kecamatan': 'Mrebet',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090001',
      'nama_desa': 'Gandasuli',
      'kode_kel': '001',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090002',
      'nama_desa': 'Kalapacung',
      'kode_kel': '002',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090003',
      'nama_desa': 'Karangmalang',
      'kode_kel': '003',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090004',
      'nama_desa': 'Banjarsari',
      'kode_kel': '004',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090005',
      'nama_desa': 'Majapura',
      'kode_kel': '005',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090006',
      'nama_desa': 'Bobotsari',
      'kode_kel': '006',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090007',
      'nama_desa': 'Karangduren',
      'kode_kel': '007',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090008',
      'nama_desa': 'Pakuncen',
      'kode_kel': '008',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090009',
      'nama_desa': 'Karangtalun',
      'kode_kel': '009',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090010',
      'nama_desa': 'Gunungkarang',
      'kode_kel': '010',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090011',
      'nama_desa': 'Talagening',
      'kode_kel': '011',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090012',
      'nama_desa': 'Tlagayasa',
      'kode_kel': '012',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090013',
      'nama_desa': 'Dagan',
      'kode_kel': '013',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090014',
      'nama_desa': 'Palumbungan',
      'kode_kel': '014',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090015',
      'nama_desa': 'Limbasari',
      'kode_kel': '015',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303090016',
      'nama_desa': 'Palumbungan Wetan',
      'kode_kel': '016',
      'kode_kec': '090',
      'kecamatan': 'Bobotsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100001',
      'nama_desa': 'Serang',
      'kode_kel': '001',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100002',
      'nama_desa': 'Kutabawa',
      'kode_kel': '002',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100003',
      'nama_desa': 'Siwarak',
      'kode_kel': '003',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100004',
      'nama_desa': 'Tlahab Lor',
      'kode_kel': '004',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100005',
      'nama_desa': 'Tlahab Kidul',
      'kode_kel': '005',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100006',
      'nama_desa': 'Karangreja',
      'kode_kel': '006',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303100007',
      'nama_desa': 'Gondang',
      'kode_kel': '007',
      'kode_kec': '100',
      'kecamatan': 'Karangreja',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110001',
      'nama_desa': 'Ponjen',
      'kode_kel': '001',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110002',
      'nama_desa': 'Buara',
      'kode_kel': '002',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110003',
      'nama_desa': 'Brakas',
      'kode_kel': '003',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110004',
      'nama_desa': 'Bungkanel',
      'kode_kel': '004',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110005',
      'nama_desa': 'Lumpang',
      'kode_kel': '005',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110006',
      'nama_desa': 'Karanggedang',
      'kode_kel': '006',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110007',
      'nama_desa': 'Kabunderan',
      'kode_kel': '007',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110008',
      'nama_desa': 'Jambudesa',
      'kode_kel': '008',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110009',
      'nama_desa': 'Maribaya',
      'kode_kel': '009',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110010',
      'nama_desa': 'Karanganyar',
      'kode_kel': '010',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110012',
      'nama_desa': 'Banjarkerta',
      'kode_kel': '012',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110013',
      'nama_desa': 'Kalijaran',
      'kode_kel': '013',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303110014',
      'nama_desa': 'Kaliori',
      'kode_kel': '014',
      'kode_kec': '110',
      'kecamatan': 'Karanganyar',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120001',
      'nama_desa': 'Karangsari',
      'kode_kel': '001',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120002',
      'nama_desa': 'Pepedan',
      'kode_kel': '002',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120003',
      'nama_desa': 'Pekiringan',
      'kode_kel': '003',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120004',
      'nama_desa': 'Grantung',
      'kode_kel': '004',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120005',
      'nama_desa': 'Rajawana',
      'kode_kel': '005',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120006',
      'nama_desa': 'Tajug',
      'kode_kel': '006',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120007',
      'nama_desa': 'Tamansari',
      'kode_kel': '007',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120008',
      'nama_desa': 'Baleraksa',
      'kode_kel': '008',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120009',
      'nama_desa': 'Tunjungmuli',
      'kode_kel': '009',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120010',
      'nama_desa': 'Kramat',
      'kode_kel': '010',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303120011',
      'nama_desa': 'Sirau',
      'kode_kel': '011',
      'kode_kec': '120',
      'kecamatan': 'Karangmoncol',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130001',
      'nama_desa': 'Wlahar',
      'kode_kel': '001',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130002',
      'nama_desa': 'Bantarbarang',
      'kode_kel': '002',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130003',
      'nama_desa': 'Karangbawang',
      'kode_kel': '003',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130004',
      'nama_desa': 'Gunungwuled',
      'kode_kel': '004',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130005',
      'nama_desa': 'Losari',
      'kode_kel': '005',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130006',
      'nama_desa': 'Bodaskarangjati',
      'kode_kel': '006',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130007',
      'nama_desa': 'Wanogara Wetan',
      'kode_kel': '007',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130008',
      'nama_desa': 'Wanogara Kulon',
      'kode_kel': '008',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130009',
      'nama_desa': 'Makam',
      'kode_kel': '009',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130010',
      'nama_desa': 'Sumampir',
      'kode_kel': '010',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130011',
      'nama_desa': 'Tanalum',
      'kode_kel': '011',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303130012',
      'nama_desa': 'Panusupan',
      'kode_kel': '012',
      'kode_kec': '130',
      'kecamatan': 'Rembang',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140001',
      'nama_desa': 'Brobot',
      'kode_kel': '001',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140002',
      'nama_desa': 'Gembong',
      'kode_kel': '002',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140003',
      'nama_desa': 'Galuh',
      'kode_kel': '003',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140004',
      'nama_desa': 'Banjaran',
      'kode_kel': '004',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140005',
      'nama_desa': 'Patemon',
      'kode_kel': '005',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140006',
      'nama_desa': 'Bojongsari',
      'kode_kel': '006',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140007',
      'nama_desa': 'Kajongan',
      'kode_kel': '007',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140008',
      'nama_desa': 'Karangbanjar',
      'kode_kel': '008',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140009',
      'nama_desa': 'Beji',
      'kode_kel': '009',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140010',
      'nama_desa': 'Pagedangan',
      'kode_kel': '010',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140011',
      'nama_desa': 'Pekalongan',
      'kode_kel': '011',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140012',
      'nama_desa': 'Metenggeng',
      'kode_kel': '012',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303140013',
      'nama_desa': 'Bumisari',
      'kode_kel': '013',
      'kode_kec': '140',
      'kecamatan': 'Bojongsari',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150004',
      'nama_desa': 'Karangsentul',
      'kode_kel': '004',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150001',
      'nama_desa': 'Karangpule',
      'kode_kel': '001',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150002',
      'nama_desa': 'Sokawera',
      'kode_kel': '002',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150003',
      'nama_desa': 'Karangjambe',
      'kode_kel': '003',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150005',
      'nama_desa': 'Bojanegara',
      'kode_kel': '005',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150006',
      'nama_desa': 'Gemuruh',
      'kode_kel': '006',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150007',
      'nama_desa': 'Dawuhan',
      'kode_kel': '007',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150008',
      'nama_desa': 'Prigi',
      'kode_kel': '008',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150009',
      'nama_desa': 'Padamara',
      'kode_kel': '009',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150010',
      'nama_desa': 'Purbayasa',
      'kode_kel': '010',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150011',
      'nama_desa': 'Kalitinggar',
      'kode_kel': '011',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150012',
      'nama_desa': 'Mipiran',
      'kode_kel': '012',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150013',
      'nama_desa': 'Karanggambas',
      'kode_kel': '013',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303150014',
      'nama_desa': 'Kalitinggar Kidul',
      'kode_kel': '014',
      'kode_kec': '150',
      'kecamatan': 'Padamara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160001',
      'nama_desa': 'Panunggalan',
      'kode_kel': '001',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160002',
      'nama_desa': 'Larangan',
      'kode_kel': '002',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160003',
      'nama_desa': 'Pasunggingan',
      'kode_kel': '003',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160004',
      'nama_desa': 'Pengadegan',
      'kode_kel': '004',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160005',
      'nama_desa': 'Karangjoho',
      'kode_kel': '005',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160006',
      'nama_desa': 'Bedagas',
      'kode_kel': '006',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160007',
      'nama_desa': 'Tumanggal',
      'kode_kel': '007',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160008',
      'nama_desa': 'Tegalpingen',
      'kode_kel': '008',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303160009',
      'nama_desa': 'Tetel',
      'kode_kel': '009',
      'kode_kec': '160',
      'kecamatan': 'Pengadegan',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170001',
      'nama_desa': 'Purbasari',
      'kode_kel': '001',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170002',
      'nama_desa': 'Sirandu',
      'kode_kel': '002',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170003',
      'nama_desa': 'Karangjambu',
      'kode_kel': '003',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170004',
      'nama_desa': 'Sanguwatang',
      'kode_kel': '004',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170005',
      'nama_desa': 'Jingkang',
      'kode_kel': '005',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303170006',
      'nama_desa': 'Danasari',
      'kode_kel': '006',
      'kode_kec': '170',
      'kecamatan': 'Karangjambu',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180001',
      'nama_desa': 'Krangean',
      'kode_kel': '001',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180002',
      'nama_desa': 'Darma',
      'kode_kel': '002',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180003',
      'nama_desa': 'Langkap',
      'kode_kel': '003',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180004',
      'nama_desa': 'Adiarsa',
      'kode_kel': '004',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180005',
      'nama_desa': 'Karangasem',
      'kode_kel': '005',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180006',
      'nama_desa': 'Karangpucung',
      'kode_kel': '006',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180007',
      'nama_desa': 'Condong',
      'kode_kel': '007',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180008',
      'nama_desa': 'Kasih',
      'kode_kel': '008',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180009',
      'nama_desa': 'Karangtengah',
      'kode_kel': '009',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180010',
      'nama_desa': 'Kertanegara',
      'kode_kel': '010',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
    {
      'kode_wilayah': '3303180011',
      'nama_desa': 'Mergasana',
      'kode_kel': '011',
      'kode_kec': '180',
      'kecamatan': 'Kertanegara',
      'kabupaten': 'Purbalingga',
      'kode_kab': '3303',
    },
  ];
}
